In [2]:
import pandas as pd
print(pd.__version__)

3.0.6

SERIES Y DATAFRAME

In [6]:
#Una SERIE Es un array ID
serie = pd.Series(
    [10,20,30],
    index=["a", "b", "c"],
    name="ventas"
)
serie

#Un DATAFRAME es un array 2D
df= pd.DataFrame({
    "producto" : ["A", "B"],
    "unidades" : [10, 20]
})

In [7]:
df

  producto  unidades
0        A        10
1        B        20

In [10]:
serie_ventas = pd.Series(
    [120,85,200,45],
    index=["enero", "febrero", "marzo", "abril"],
    name = "ventas"
)
serie_ventas

enero      120
febrero     85
marzo      200
abril       45
Name: ventas, dtype: int64

In [11]:
serie_ventas.mean()

np.float64(112.5)

In [12]:
serie_ventas.min()

np.int64(45)

DARAFRAME
CREAR DATAFRAME DESDE UN DICCIONARIO

In [13]:
df = pd.DataFrame({
    "producto" : ["Laptop", "Monitor", "Teclado"],
    "unidades" : [3, 7, 12],
    "precio": [1200, 320, 95]
})

df

  producto  unidades  precio
0   Laptop         3    1200
1  Monitor         7     320
2  Teclado        12      95

### Desde Una lista de Diccionarios

In [14]:
df2 = pd.DataFrame(
    [
        {"producto": "laptop", "unidades":3, "precio":1200},
        {"prodcuto": "monitor", "unidades":7, "precio":320}
    ]
)

df2

  producto  unidades  precio prodcuto
0   laptop         3    1200      NaN
1      NaN         7     320  monitor

### Desde una lista de listas

In [16]:
df3 = pd.DataFrame(
    [
        ["laptop", 3, 1200],
        ["Monitor",7 ,320]
    ],
    columns = ["producto", "unidades", "precio"]
)

df3

  producto  unidades  precio
0   laptop         3    1200
1  Monitor         7     320

In [ ]:
df["impore"] = df["undiades"]*df["precio"]
df

KeyError: 'undiades'